name: Build for Linux
on:
  push:
    paths-ignore:
      - '.github/workflows/*.yml'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
           fetch-depth: 0
        - name: Run cmake
          run: cmake -G "CodeBlocks - Unix Makefiles" -S . -B build
        - name: Run make
          run: |
              cd build
              make
        - name: Generate version
          run: echo version=0.${{ github.run_number }} >> $GITHUB_ENV
        - name: Create release
          uses: ncipollo/release-action@v1.8.6
          with:
            artifacts: "*/devmode-toggle"
            allowUpdates: true
            tag: ${{ env.version }}
            token: ${{ secrets.GITHUB_TOKEN }}
